apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  interval: 10m0s
  path: ./apps                      # Tell Flux to look at your new /apps folder
  prune: true                       # Automatically delete resources if you delete their files
  sourceRef:
    kind: GitRepository
    name: flux-system               # Reuses the Git source created during bootstrap
