apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: qbitorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-data
        persistentVolumeClaim:
          claimName: media
      containers:
      - env:
        - name: TZ
          value: Europe/Dublin
        image: jellyfin/jellyfin:10.11.11
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http-tcp
          protocol: TCP
        - containerPort: 8920
          name: https-tcp
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 7359
          name: discovery-udp
          protocol: UDP
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "4000m"
            memory: "16Gi"
            devic.es/amd-render: 1
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /config
          name: jellyfin-config
        - mountPath: /data
          name: jellyfin-data
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: qbitorrent
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: qbitorrent
spec:
  entryPoints:
    - web 
  routes:
    - match: Host(`jellyfin.homelab`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-tailscale
  namespace: qbitorrent
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyfin
  rules:
    - host: jellyfin
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096

