---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: qbitorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      annotations:
        obi.instrument: "true"
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.19
          env:
            - name: TZ
              value: Etc/UTC
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: data
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: qbitorrent
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: qbitorrent
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sonarr.homelab`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989

