apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tls
  namespace: traefik-external
spec:
  secretName: domain-tls
  dnsNames:
    - "*.ozzywalsh.com"
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
