---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: qbitorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      annotations:
        obi.instrument: "true"
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:v3.41.1
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: VPN_SERVICE_PROVIDER
            value: protonvpn

          - name: VPN_TYPE
            value: wireguard

          # Store these in a Secret in production
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: proton-wireguard
                key: private-key

          - name: WIREGUARD_ADDRESSES
            value: "10.2.0.2/32"

          # Optional
          - name: TZ
            value: Europe/Dublin

        volumeMounts:
          - name: tun
            mountPath: /dev/net/tun

        ports:
          - containerPort: 8080
          - containerPort: 31456
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.5.2
          env:
            - name: TZ
              value: Etc/UTC
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: qbitorrent
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: qbitorrent
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prowlarr.homelab`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696

