apiVersion: v1
kind: Namespace
metadata:
  name: qbitorrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  namespace: qbitorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: qbitorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbitorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbitorrent
  template:
    metadata:
      labels:
        app: qbitorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:5.2.2
        env:
        - name: PUID
          value: "1000" # Maps to your host user
        - name: PGID
          value: "1000" # Maps to your host group
        - name: TZ
          value: "Europe/Dublin"
        - name: WEBUI_PORT
          value: "8080"
        ports:
          - containerPort: 8080
          - containerPort: 58124
        volumeMounts:
          - name: config
            mountPath: /config
          - name: downloads
            mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-peer
  namespace: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbitorrent
  ports:
    - name: torrent-tcp
      protocol: TCP
      port: 31456
      targetPort: 31456
      nodePort: 31456
    - name: torrent-udp
      protocol: UDP
      port: 31456
      targetPort: 31456
      nodePort: 31456
