---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: qbitorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      annotations:
        obi.instrument: "true"
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.3.0
          env:
            - name: TZ
              value: Etc/UTC
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: nfs-jellyfin-data
              mountPath: /data/downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: qbitorrent-downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: qbitorrent
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: qbitorrent
spec:
  entryPoints:
    - web
  routes:
    - match: Host('radarr.homelab')
      kind: Rule
      services:
        - name: radarr
